### PR TITLE
Update node version and protagonist

### PR DESCRIPTION
**Pull request by memoxmrdl**

### CODE REVIEW

**Comment by o5** [comment]
Thanks for PR! Could you update also Dockerfile for Node 14 a fix tests? I cannot merge without it :/

**Comment by memoxmrdl** [comment]
@o5 Hi! yes of course! let me it change node from Dockerfile and fix tests

**Comment by o5** [comment]
@mariochavez I'm late but have news 😏 

It was [not so easy](https://github.com/slimapi/apib2json/commit/6ac97f38092a66b366a5f5d675c960611e5869e5) to me but I've to say I'm now satisfied with converting results on my real APIs 🎉  

* The results should be better now (group and title in meta should be filled when available)
* The results from apiary's parser have different structures if document has not `GROUP` statement (It's standard for my APIs, so I changed it in the fixtures folder)
* JSON Schema Draft-07 is used now!

Please try it and compare thoroughly results from new version (`0.3.0-3-g6ac97f3`) and old (`0.1.8`) 🙏 

```bash
docker run --rm -i slimapi/apib2json:0.3.0-3-g6ac97f3 --pretty < documentation.md > output.new.json
docker run --rm -i slimapi/apib2json:0.1.8 --pretty < documentation.md > output.old.json
diff output.new.json output.old.json
```

I would like to release version `1.0` 😎

**Comment by o5** [comment]
@memoxmrdl Please let me know if you are possible to try the version (which I mentioned in my previous comment) into new PR https://github.com/slimapi/apib2json/pull/10

I'm closing this, thank you!

**Pull request closed without merging**
